language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
cache: pip
script: nosetests
install:
  - if [[ $TRAVIS_PYTHON_VERSION < 3.4 ]]; then pip install enum34; fi
  - pip install -r requirements.txt
